### ISSUE TITLE
Not able tto import tensorlight

### ISSUE THREAD

**Issue by anshulbshah** [bsautermeister/tensorlight#1]
I tried installing tensorlight using the instructions given in the readme file.
I get the following error when I try to import tensorlight in python : 

Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorlight/__init__.py", line 24, in <module>
    import tensorlight.utils
ImportError: No module named 'tensorlight.utils'

**Comment by anshulbshah** [comment]
Worked with python2.7

**Comment by b3nk4n** [comment]
Hi @anshulbshah !

Thank you for pointing this out. Yes, when I implemented and used this library for my Master's thesis, I was restricted my our admins to use Python 2.7 at university. Furthermore, in the very early versions of TensorFlow (0.6, 0.7), version 2.7 of Python was recommended by Google.

I try to find some time in the near future to update the code to make it working in both versions of Python.
